[project]
name = "learning-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "striker-14", email = "pranaypartapsingh14@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.3.18",
    "langchain-google-genai>=4.3.7",
    "pip>=26.2.1",
    "python-dotenv>=1.2.3",
]

[project.scripts]
learning-langchain = "learning_langchain:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
